# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI (NFT Upload + Other)

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: TEST_SECRET
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py install
    - name: First test
      run: |
        python -m samila
    - name: Test requirements Installation
      run: |
        python otherfiles/requirements-splitter.py
        pip install --upgrade --upgrade-strategy=only-if-needed -r test-requirements.txt
    - name: Test with pytest (+ NFT upload test)
      run: |
        python -m pytest test --cov=samila --cov-report=term
      env:
        NFT_STORAGE_API_KEY: ${{ secrets.NFT_STORAGE_API_KEY }}
    - name: Version check
      run: |
        python otherfiles/version_check.py
    - name: Other tests
      run: |
        python -m vulture samila/ setup.py --min-confidence 65 --exclude=__init__.py --sort-by-size
        python -m bandit -r samila -s B311
        python -m pydocstyle -v --match-dir=samila
    - name: Codecov
      run: |
        codecov
